const redBasics = ["red/Bash.png"]
const redCommons = [
  "red/Anger.png",
  "red/Armaments.png",
  "red/Body_Slam.png",
  "red/Clash.png",
  "red/Cleave.png",
  "red/Clothesline.png",
  "red/Flex.png",
  "red/Havoc.png",
  "red/Headbutt.png",
  "red/Heavy_Blade.png",
  "red/Iron_Wave.png",
  "red/Perfected_Strike.png",
  "red/Pommel_Strike.png",
  "red/Shrug_it_Off.png",
  "red/Sword_Boomerang.png",
  "red/Thunderclap.png",
  "red/True_Grit.png",
  "red/Twin_Strike.png",
  "red/Warcry.png",
  "red/Wild_Strike.png",
]
const redUncommons = [
  "red/Battle_Trance.png",
  "red/Blood_for_Blood.png",
  "red/Bloodletting.png",
  "red/Burning_Pact.png",
  "red/Carnage.png",
  "red/Combust.png",
  "red/Dark_Embrace.png",
  "red/Disarm.png",
  "red/Dropkick.png",
  "red/Dual_Wield.png",
  "red/Entrench.png",
  "red/Evolve.png",
  "red/Feel_No_Pain.png",
  "red/Fire_Breathing.png",
  "red/Flame_Barrier.png",
  "red/Ghostly_Armor.png",
  "red/Hemokinesis.png",
  "red/Infernal_Blade.png",
  "red/Inflame.png",
  "red/Intimidate.png",
  "red/Metallicize.png",
  "red/Power_Through.png",
  "red/Pummel.png",
  "red/Rage.png",
  "red/Rampage.png",
  "red/Reckless_Charge.png",
  "red/Rupture.png",
  "red/Searing_Blow.png",
  "red/Second_Wind.png",
  "red/Seeing_Red.png",
  "red/Sentinel.png",
  "red/Sever_Soul.png",
  "red/Shockwave.png",
  "red/Spot_Weakness.png",
  "red/Uppercut.png",
  "red/Whirlwind.png",
]
const redRares = [
  "red/Barricade.png",
  "red/Berserk.png",
  "red/Bludgeon.png",
  "red/Brutality.png",
  "red/Corruption.png",
  "red/Demon_Form.png",
  "red/Double_Tap.png",
  "red/Exhume.png",
  "red/Feed.png",
  "red/Fiend_Fire.png",
  "red/Immolate.png",
  "red/Impervious.png",
  "red/Juggernaut.png",
  "red/Limit_Break.png",
  "red/Offering.png",
  "red/Reaper.png",
]

const greenBasics = [
  "green/Neutralize.png",
  "green/Survivor.png",
]
const greenCommons = [
  "green/Acrobatics.png",
  "green/Backflip.png",
  "green/Bane.png",
  "green/Blade_Dance.png",
  "green/Cloak_And_Dagger.png",
  "green/Dagger_Spray.png",
  "green/Dagger_Throw.png",
  "green/Deadly_Poison.png",
  "green/Deflect.png",
  "green/Dodge_and_Roll.png",
  "green/Flying_Knee.png",
  "green/Outmaneuver.png",
  "green/Piercing_Wail.png",
  "green/Poisoned_Stab.png",
  "green/Prepared.png",
  "green/Quick_Slash.png",
  "green/Slice.png",
  "green/Sneaky_Strike.png",
  "green/Sucker_Punch.png",
]
const greenUncommons = [
  "green/Accuracy.png",
  "green/All-Out_Attack.png",
  "green/Backstab.png",
  "green/Blur.png",
  "green/Bouncing_Flask.png",
  "green/Calculated_Gamble.png",
  "green/Caltrops.png",
  "green/Catalyst.png",
  "green/Choke.png",
  "green/Concentrate.png",
  "green/Crippling_Cloud.png",
  "green/Dash.png",
  "green/Distraction.png",
  "green/Endless_Agony.png",
  "green/Escape_Plan.png",
  "green/Eviscerate.png",
  "green/Expertise.png",
  "green/Finisher.png",
  "green/Flechettes.png",
  "green/Footwork.png",
  "green/Heel_Hook.png",
  "green/Infinite_Blades.png",
  "green/Leg_Sweep.png",
  "green/Masterful_Stab.png",
  "green/Noxious_Fumes.png",
  "green/Predator.png",
  "green/Reflex.png",
  "green/Riddle_With_Holes.png",
  "green/Setup.png",
  "green/Skewer.png",
  "green/Tactician.png",
  "green/Terror.png",
  "green/Well-Laid_Plans.png",
]
const greenRares = [
  "green/A_Thousand_Cuts.png",
  "green/Adrenaline.png",
  "green/After_Image.png",
  "green/Alchemize.png",
  "green/Bullet_Time.png",
  "green/Burst.png",
  "green/Corpse_Explosion.png",
  "green/Die_Die_Die.png",
  "green/Doppelganger.png",
  "green/Envenom.png",
  "green/Glass_Knife.png",
  "green/Grand_Finale.png",
  "green/Malaise.png",
  "green/Nightmare.png",
  "green/Phantasmal_Killer.png",
  "green/Storm_of_Steel.png",
  "green/Tools_of_the_Trade.png",
  "green/Unload.png",
  "green/Wraith_Form.png",
]

const blueBasics = [
  "blue/Dualcast.png",
  "blue/Zap.png",
]
const blueCommons = [
  "blue/Ball_Lightning.png",
  "blue/Barrage.png",
  "blue/Beam_Cell.png",
  "blue/Charge_Battery.png",
  "blue/Claw.png",
  "blue/Cold_Snap.png",
  "blue/Compile_Driver.png",
  "blue/Coolheaded.png",
  "blue/Go_for_the_Eyes.png",
  "blue/Hologram.png",
  "blue/Leap.png",
  "blue/Rebound.png",
  "blue/Recursion.png",
  "blue/Stack.png",
  "blue/Steam_Barrier.png",
  "blue/Streamline.png",
  "blue/Sweeping_Beam.png",
  "blue/TURBO.png",
]
const blueUncommons = [
  "blue/Aggregate.png",
  "blue/Auto-Shields.png",
  "blue/Blizzard.png",
  "blue/Boot_Sequence.png",
  "blue/Bullseye.png",
  "blue/Capacitor.png",
  "blue/Chaos.png",
  "blue/Chill.png",
  "blue/Consume.png",
  "blue/Darkness.png",
  "blue/Defragment.png",
  "blue/Doom_and_Gloom.png",
  "blue/Double_Energy.png",
  "blue/Equilibrium.png",
  "blue/FTL.png",
  "blue/Force_Field.png",
  "blue/Fusion.png",
  "blue/Genetic_Algorithm.png",
  "blue/Glacier.png",
  "blue/Heatsinks.png",
  "blue/Hello_World.png",
  "blue/Loop.png",
  "blue/Melter.png",
  "blue/Overclock.png",
  "blue/Recycle.png",
  "blue/Reinforced_Body.png",
  "blue/Reprogram.png",
  "blue/Rip_and_Tear.png",
  "blue/Scrape.png",
  "blue/Self_Repair.png",
  "blue/Skim.png",
  "blue/Static_Discharge.png",
  "blue/Storm.png",
  "blue/Sunder.png",
  "blue/Tempest.png",
  "blue/White_Noise.png",
]
const blueRares = [
  "blue/All_for_One.png",
  "blue/Amplify.png",
  "blue/Biased_Cognition.png",
  "blue/Buffer.png",
  "blue/Core_Surge.png",
  "blue/Creative_AI.png",
  "blue/Echo_Form.png",
  "blue/Electrodynamics.png",
  "blue/Fission.png",
  "blue/Hyperbeam.png",
  "blue/Machine_Learning.png",
  "blue/Meteor_Strike.png",
  "blue/Multi-Cast.png",
  "blue/Rainbow.png",
  "blue/Reboot.png",
  "blue/Seek.png",
  "blue/Thunder_Strike.png",
]

const purpleBasics = [
  "purple/Eruption.png",
  "purple/Vigilance.png",
]
const purpleCommons = [
  "purple/Bowling_Bash.png",
  "purple/Consecrate.png",
  "purple/Crescendo.png",
  "purple/Crush_Joints.png",
  "purple/Cut_Through_Fate.png",
  "purple/Empty_Body.png",
  "purple/Empty_Fist.png",
  "purple/Evaluate.png",
  "purple/Flurry_of_Blows.png",
  "purple/Flying_Sleeves.png",
  "purple/Follow-Up.png",
  "purple/Halt.png",
  "purple/Just_Lucky.png",
  "purple/Pressure_Points.png",
  "purple/Prostrate.png",
  "purple/Protect.png",
  "purple/Sash_Whip.png",
  "purple/Third_Eye.png",
  "purple/Tranquility.png",
]
const purpleUncommons = [
  "purple/Battle_Hymn.png",
  "purple/Carve_Reality.png",
  "purple/Collect.png",
  "purple/Conclude.png",
  "purple/Deceive_Reality.png",
  "purple/Empty_Mind.png",
  "purple/Fasting.png",
  "purple/Fear_No_Evil.png",
  "purple/Foreign_Influence.png",
  "purple/Foresight.png",
  "purple/Indignation.png",
  "purple/Inner_Peace.png",
  "purple/Like_Water.png",
  "purple/Meditate.png",
  "purple/Mental_Fortress.png",
  "purple/Nirvana.png",
  "purple/Perseverance.png",
  "purple/Pray.png",
  "purple/Reach_Heaven.png",
  "purple/Rushdown.png",
  "purple/Sanctity.png",
  "purple/Sands_of_Time.png",
  "purple/Signature_Move.png",
  "purple/Simmering_Fury.png",
  "purple/Study.png",
  "purple/Swivel.png",
  "purple/Talk_to_the_Hand.png",
  "purple/Tantrum.png",
  "purple/Wallop.png",
  "purple/Wave_of_the_Hand.png",
  "purple/Weave.png",
  "purple/Wheel_Kick.png",
  "purple/Windmill_Strike.png",
  "purple/Worship.png",
  "purple/Wreath_of_Flame.png",
]
const purpleRares = [
  "purple/Alpha.png",
  "purple/Blasphemy.png",
  "purple/Brilliance.png",
  "purple/Conjure_Blade.png",
  "purple/Deus_Ex_Machina.png",
  "purple/Deva_Form.png",
  "purple/Devotion.png",
  "purple/Establishment.png",
  "purple/Judgment.png",
  "purple/Lesson_Learned.png",
  "purple/Master_Reality.png",
  "purple/Omniscience.png",
  "purple/Ragnarok.png",
  "purple/Scrawl.png",
  "purple/Spirit_Shield.png",
  "purple/Vault.png",
  "purple/Wish.png",
]

export const colorlessUncommons = [
  "colorless/Bandage_Up.png",
  "colorless/Blind.png",
  "colorless/Dark_Shackles.png",
  "colorless/Deep_Breath.png",
  "colorless/Discovery.png",
  "colorless/Dramatic_Entrance.png",
  "colorless/Enlightenment.png",
  "colorless/Finesse.png",
  "colorless/Flash_of_Steel.png",
  "colorless/Forethought.png",
  "colorless/Good_Instincts.png",
  "colorless/Impatience.png",
  "colorless/Jack_Of_All_Trades.png",
  "colorless/Madness.png",
  "colorless/Mind_Blast.png",
  "colorless/Panacea.png",
  "colorless/Panic_Button.png",
  "colorless/Purity.png",
  "colorless/Swift_Strike.png",
  "colorless/Trip.png",
]

export const curses = [
  "curse/Clumsy.png",
  "curse/Decay.png",
  "curse/Doubt.png",
  "curse/Injury.png",
  "curse/Normality.png",
  "curse/Pain.png",
  "curse/Parasite.png",
  "curse/Regret.png",
  "curse/Shame.png",
  "curse/Writhe.png",
]

export const redCards = {
  basics: redBasics,
  commons: redCommons,
  uncommons: redUncommons,
  rares: redRares,
 } ;

export const greenCards = {
  basics: greenBasics,
  commons: greenCommons,
  uncommons: greenUncommons,
  rares: greenRares,
}

export const blueCards = {
  basics: blueBasics,
  commons: blueCommons,
  uncommons: blueUncommons,
  rares: blueRares,
}

export const purpleCards = {
  basics: purpleBasics,
  commons: purpleCommons,
  uncommons: purpleUncommons,
  rares: purpleRares,
}
